## Plain Language Summary

A series of phenomena such as early flowering of plants and
early migratory birds are suggesting that the traditional four seasons may have changed. We focus on how
the four seasons changed during 1952–2011 and will change by the end of this century in the warming
Northern Hemisphere midlatitudes. We find that lengths and start dates of the four seasons have changed,
and the changes will be amplified in the future. Over the period of 1952–2011, <i><u>the length of summer
increased from 78 to 95 days and that of spring, autumn and winter decreased from 124 to 115, 87 to 82,
and 76 to 73 days, respectively. In addition, summer is projected to last nearly half a year, but winter less
than 2 months by 2100</u></i>. Such changes can trigger a chain of reactions in agriculture, policy-making for
agricultural management and disaster prevention requires adjustment accordingly. The seasonal-related
topics involving ecology, the ocean and the atmosphere also need to be revisited.

#### Here, we consider how the four seasons changed during 1952–2011 and will change by the end of this century in the warming Northern Hemisphere midlatitudes (30–60°N), where the division of the four seasons based on temperature is readily available.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import netCDF4 as nc

ds = nc.Dataset("D:\\Earth.Org\\4seasons\\data\\HadGHCND_1949-2011_GSL.nc")
ds.__dict__

{'Title': 'index GSL, 1 level -- Annual value.',
 'author': 'Hongang Yang - hongang.yang@unsw.edu.au',
 'history': 'Created from Fclimdex version 3.1.1',
 'units': 'days',
 'long_name': 'Growing season Length'}

In [4]:
for var in ds.variables.values():
    print(var)

<class 'netCDF4._netCDF4.Variable'>
float32 lon(lon)
    long_name: Longitude
    units: degrees_east
    axis: X
unlimited dimensions: 
current shape = (96,)
filling on, default _FillValue of 9.969209968386869e+36 used
<class 'netCDF4._netCDF4.Variable'>
float32 lat(lat)
    long_name: Latitude
    units: degrees_north
    axis: Y
unlimited dimensions: 
current shape = (73,)
filling on, default _FillValue of 9.969209968386869e+36 used
<class 'netCDF4._netCDF4.Variable'>
int32 time(time)
    units: day as %Y%m%d.%f
    calendar: proleptic_gregorian
unlimited dimensions: 
current shape = (63,)
filling on, default _FillValue of -2147483647 used
<class 'netCDF4._netCDF4.Variable'>
float32 Annual(time, lat, lon)
    missing_value: -999.9
    _FillValue: -999.9
unlimited dimensions: 
current shape = (63, 73, 96)
filling on


In [5]:
lon = np.array(ds['lon'][:])
lon

array([-180.  , -176.25, -172.5 , -168.75, -165.  , -161.25, -157.5 ,
       -153.75, -150.  , -146.25, -142.5 , -138.75, -135.  , -131.25,
       -127.5 , -123.75, -120.  , -116.25, -112.5 , -108.75, -105.  ,
       -101.25,  -97.5 ,  -93.75,  -90.  ,  -86.25,  -82.5 ,  -78.75,
        -75.  ,  -71.25,  -67.5 ,  -63.75,  -60.  ,  -56.25,  -52.5 ,
        -48.75,  -45.  ,  -41.25,  -37.5 ,  -33.75,  -30.  ,  -26.25,
        -22.5 ,  -18.75,  -15.  ,  -11.25,   -7.5 ,   -3.75,    0.  ,
          3.75,    7.5 ,   11.25,   15.  ,   18.75,   22.5 ,   26.25,
         30.  ,   33.75,   37.5 ,   41.25,   45.  ,   48.75,   52.5 ,
         56.25,   60.  ,   63.75,   67.5 ,   71.25,   75.  ,   78.75,
         82.5 ,   86.25,   90.  ,   93.75,   97.5 ,  101.25,  105.  ,
        108.75,  112.5 ,  116.25,  120.  ,  123.75,  127.5 ,  131.25,
        135.  ,  138.75,  142.5 ,  146.25,  150.  ,  153.75,  157.5 ,
        161.25,  165.  ,  168.75,  172.5 ,  176.25], dtype=float32)

In [6]:
lat = np.array(ds['lat'][:])
lat

array([ 90. ,  87.5,  85. ,  82.5,  80. ,  77.5,  75. ,  72.5,  70. ,
        67.5,  65. ,  62.5,  60. ,  57.5,  55. ,  52.5,  50. ,  47.5,
        45. ,  42.5,  40. ,  37.5,  35. ,  32.5,  30. ,  27.5,  25. ,
        22.5,  20. ,  17.5,  15. ,  12.5,  10. ,   7.5,   5. ,   2.5,
         0. ,  -2.5,  -5. ,  -7.5, -10. , -12.5, -15. , -17.5, -20. ,
       -22.5, -25. , -27.5, -30. , -32.5, -35. , -37.5, -40. , -42.5,
       -45. , -47.5, -50. , -52.5, -55. , -57.5, -60. , -62.5, -65. ,
       -67.5, -70. , -72.5, -75. , -77.5, -80. , -82.5, -85. , -87.5,
       -90. ], dtype=float32)

In [7]:
ds.variables['Annual'].set_auto_mask(False)

In [18]:
time = np.array(ds['time'][:])
time

array([19490100, 19500100, 19510100, 19520100, 19530100, 19540100,
       19550100, 19560100, 19570100, 19580100, 19590100, 19600100,
       19610100, 19620100, 19630100, 19640100, 19650100, 19660100,
       19670100, 19680100, 19690100, 19700100, 19710100, 19720100,
       19730100, 19740100, 19750100, 19760100, 19770100, 19780100,
       19790100, 19800100, 19810100, 19820100, 19830100, 19840100,
       19850100, 19860100, 19870100, 19880100, 19890100, 19900100,
       19910100, 19920100, 19930100, 19940100, 19950100, 19960100,
       19970100, 19980100, 19990100, 20000100, 20010100, 20020100,
       20030100, 20040100, 20050100, 20060100, 20070100, 20080100,
       20090100, 20100100, 20110100])

In [12]:
temp = np.array(ds.variables['Annual'])
temp[0][0]

array([-999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
       -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9],
      dtype=float32)

In [52]:
ds.variables['Annual'][62, 12:21,:]

array([[-999.9, -999.9, -999.9, -999.9, -999.9,  145. ,  148. ,  153. ,
         155. ,  152. ,  143. ,  140. ,  148. ,  159. ,  164. ,  163. ,
         163. ,  160. ,  159. ,  157. ,  155. ,  153. ,  150. , -999.9,
        -999.9, -999.9, -999.9, -999.9,  111. ,   94. , -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9,  223. ,  215. ,  216. , -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9],
       [-999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9, -999.9,
        -999.9, -999.9, -999.9, -999.9,  186. ,  180. ,  178. ,